import type { Metadata } from "next";

import "./globals.css";
import { AppContextProvider } from "./context/AppContext";
import NavWrapper from "./components/student/NavWrapper";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "LMSify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AppContextProvider>
        <html lang="en">
          <body className="antialiased">
            <NavWrapper />
            {children}
          </body>
        </html>
      </AppContextProvider>
    </ClerkProvider>
  );
}
